### ISSUE TITLE
Gemfile.lock between platforms

### ISSUE THREAD

**Issue by zflat** [bikebike/BikeBike#10]
There are issues with using bundler between platforms where the Gemfile.lock file can't be shared. 
Here is the feature request to resolve in bundler:
https://github.com/bundler/bundler-features/issues/4

When I run `bundle install` a ton of changes happen to my Gemfile.lock. It doesn't make sense for me to check in my changes if other platforms will want to override later. Here is one strategy that may help:
https://github.com/bundler/bundler/issues/646#issuecomment-10323368

http://stackoverflow.com/questions/10764199/develop-on-windows-run-unicorn-in-production-on-heroku

Also, we should all check and see what version of bundler we have running on our machines and make sure it is up to date.

**Comment by G0dwin** [comment]
For now I added Gemfile.lock to gitignore, perhaps not the best long term solution but I needed to make sure lingua_franca and bumbleberry were updated regularly.
