### ISSUE TITLE
populating with dummy data for development

### ISSUE THREAD

**Issue by zflat** [bikebike/BikeBike#18]
I would like to load or populate the application with dummy data so that I can interact with the application. It is nice to have the cucumber tests to go through scenarios, but I like to be able to recreate some of the failing scenarios on my own to get more context on where it is failing.

How have you been interacting with the application so far in development? Have you manually created conferences, locations, ect? Or do you have a script to load dummy data?

**Comment by G0dwin** [comment]
Now that the site can be spun up without data and conferences can be created as an administrator on the site, I don't think we need this anymore. New devs can get the site up and start populating with their own data.
