### ISSUE TITLE
RESTful routes regarding conference types

### ISSUE THREAD

**Issue by zflat** [bikebike/BikeBike#20]
Routes are being coerced into not being RESTful. One problem I am running into is that when I browse to /conferences/new the routes process it to ConferencesController#index with Parameters: {"conference_type"=>"new"}

I think we can still 'namespace' our conferences and remain restful. Basically, it looks like the routes are arranged so that international conferences are prefixed with 'bikebike' and regional are prefixed with 'regional.'

If we want to have a 'namespace' for conferences then maybe we can do something like define the conferences resource as:

<code> resources :conferences, :param => :slug, :path => 'conferences/:conference_type' </code>

This will eliminate the need to define a conference_types resources, which does not seem to be used anyway. I'll work on an updated conferences route.

**Comment by G0dwin** [comment]
The conference type part of the route was removed this year.
