### ISSUE TITLE
Send some form of confirmation when a user registers

### ISSUE THREAD

**Issue by subletter** [bikebike/BikeBike#202]
Just registered for the conference (I think) but have no confirmation of having done so. Got to the last page about workshops and the workflow just kinda ended there.

**Comment by G0dwin** [comment]
Woah, thanks for filing a github issue directly.

That feature does exist currently, you should get an email once you get to the payment page. Can you confirm that the email didn't go to your junk? I need to do some work to our mail server to prevent emails from landing in junk boxes, right now they are often getting filtered by clients.

If it's not there, can you send me your user name or email address so that I can trace your data in the logs?

**Comment by subletter** [comment]
I got an email for verifying that I'm a real person with the body "Hello! To gain access to registration..." and clicking on the button went fine. The only other email I got was a receipt directly from PayPal. I checked my spam folders, nothing.

**Comment by G0dwin** [comment]
Hmm, ok can I get your user name or something else to determine who you are in the system so that I can trace what happened?

**Comment by G0dwin** [comment]
Ok, I have your details now, I'll look into it.

**Comment by G0dwin** [comment]
Just tried reproducing in our staging environment but I did receive a confirmation. I need to look into this more closely when I get home. Right now it looks as though the email is being sent once registration is paid for: https://github.com/bikebike/BikeBike/blob/master/app/controllers/conferences_controller.rb#L204 but really registration is complete once the "Registration Info" form is submitted. My hunch is that system is getting into a confused state once the payment process begins.

**Comment by subletter** [comment]
Yeah, that line looks pretty clear. I'd offer to lend more of a hand if I were a Ruby-person...

**Comment by G0dwin** [comment]
Moved the spot where we send mail from the controller to the model where it can check to see if it's status has changed: https://github.com/bikebike/BikeBike/blob/master/app/models/conference_registration.rb#L46-L56

Verified that the email is sent directly after pressing the "Register" button on the "Registration Info" page.
