### ISSUE TITLE
translation-info.yml gets cleared out when running cucumber

### ISSUE THREAD

**Issue by zflat** [bikebike/BikeBike#8]
The file config/locals/translation-info.yml gets cleared out when I run cucumber tests. 

As mentioned in https://github.com/bikebike/BikeBike/issues/6 I81n is handled in a unique way. I need to read through the code to see what is going on, but I am wondering is there seed data that I need to load? Or is the I18n backend not loading from the cache?

**Comment by G0dwin** [comment]
Translation logic was moved to the lingua_franca gem, it seems to be working as expected now.
