### ISSUE TITLE
Rich edit controls are not accessible on Android devices

### ISSUE THREAD

**Issue by G0dwin** [bikebike/BikeBike#81]
Still need to look into iOS but on Android the controls are covered by native selection utilities (copy, paste, select all...) and the controls appear to far to the right to be useful when the selection is on the right of the display.

**Comment by LinguaFrancaTranslator** [comment]
I think what makes the most sense here is to force the controls to display at the bottom of the screen for mobile devices. 
On 12 Jun 2016 11:05 a.m., Godwin <notifications@github.com> wrote:Still need to look into iOS but on Android the controls are covered by native selection utilities (copy, paste, select all...) and the controls appear to far to the right to be useful when the selection is on the right of the display.

**Comment by G0dwin** [comment]
I positioned the controls at the top of the screen as the bottom is already being used by the main menu.
